services:
    custom_post_type_api:
        class: \PoP\ContentWP\TypeAPIs\CustomPostTypeAPI
        public: true
    custom_post_type_list_api:
        class: \PoP\ContentWP\TypeAPIs\CustomPostTypeListAPI
        public: true
